# Generated by Django 4.2.6 on 2023-10-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
    ]
