# Generated by Django 4.2.6 on 2023-10-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0003_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["completed", "-created_at"]},
        ),
    ]
